---
name: "Setup Umka"
author: Yevhen Fabizhevskyi
description: "This action sets up Umka scripting language interpreter."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "Umka version."
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Collect info
      if: ${{ runner.os != 'macOS' }}
      id: info
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: |
        if [ "${RUNNER_OS}" = "Linux" ]; then
          bin_name=linux
          exec_name=umka
        else
          bin_name=windows_mingw
          exec_name=umka.exe
        fi
        echo "umka-installed=$(if command -v "${exec_name}" >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
        echo "file-name=umka_${INPUT_VERSION}_${bin_name}" >> "$GITHUB_OUTPUT"

        umka_bin_dir="$(date +%s)"
        umka_bin_path="${GITHUB_WORKSPACE}/${umka_bin_dir}"
        mkdir -p "${umka_bin_path}"
        echo "umka-dir=${umka_bin_dir}" >> "$GITHUB_OUTPUT"
        echo "umka-path=${umka_bin_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download umka
      if: ${{ steps.info.outputs.umka-installed == 'false' }}
      uses: robinraju/release-downloader@v1
      with:
        repository: "vtereshkov/umka-lang"
        latest: "${{ inputs.version == 'latest' }}"
        tag: "v${{ inputs.version }}"
        fileName: "${{ steps.info.outputs.file-name }}.zip"
        tarBall: "false"
        zipBall: "true"
        extract: "true"
        out-file-path: "${{ steps.info.outputs.umka-dir }}"
    - name: Install umka
      if: ${{ steps.info.outputs.umka-installed == 'false' }}
      run: |
        ls -la .
        # unzip "${{ steps.info.outputs.file-name }}.zip"
        # rm -f "${{ steps.info.outputs.file-name }}.zip"
        if [ "${RUNNER_OS}" != "Windows" ]; then
          chmod +x "${{ steps.info.outputs.umka-path }}/${{ steps.info.outputs.file-name }}/umka"
        fi
        echo "${{ steps.info.outputs.umka-path }}/${{ steps.info.outputs.file-name }}" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.umka-path }}
