---
name: "Setup Umka"
author: Yevhen Fabizhevskyi
description: "This action sets up Umka scripting language interpreter."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: Umka version. Defaults to the latest version.
    required: false
    default: "latest"
  force:
    description: |
      If "false" skips installation if umka is already installed. If "true"
      installs umka in any case. Defaults to "false".
    required: false
    default: "false"
  github-token:
    description: |
      GitHub token that is used to send requests to GitHub API such as downloading
      asset. Defaults to the token provided by GitHub Actions environment.
    required: false
    default: ${{ github.token }}
outputs:
  installed:
    description: Whether umka was installed or not.
    value: "${{ steps.install-umka.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Download binary
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: download-binary
      uses: robinraju/release-downloader@v1
      with:
        repository: "vtereshkov/umka-lang"
        latest: "${{ inputs.version == 'latest' }}"
        tag: "${{ inputs.version != 'latest' && format('v{0}', inputs.version) || '' }}"
        fileName: "umka_*_${{ runner.os == 'Linux' && 'linux' || 'windows_mingw' }}.zip"
        extract: "true"
        out-file-path: "${{ steps.info.outputs.bin-dir }}"
        token: "${{ inputs.github-token }}"

    - name: Install umka
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-umka
      run: |
        tag_name="${{ steps.download-binary.outputs.tag_name }}"
        bin_path="${{ steps.info.outputs.bin-path }}/umka_${tag_name#v}_${{ runner.os == 'Linux' && 'linux' || 'windows_mingw' }}"
        if [ "${RUNNER_OS}" != "Windows" ]; then
          chmod +x "${bin_path}/umka"
          ${bin_path}/umka --version
        fi
        echo "${bin_path}" >> "$GITHUB_PATH"
      shell: sh

    - name: Print version
      run: umka --version
      shell: sh
