---
name: "Setup Umka"
author: Yevhen Fabizhevskyi
description: "This action sets up Umka scripting language interpreter."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: Umka version.
    required: false
    default: "latest"
  github-token:
    description: |
      GitHub token that is used to send requests to GitHub API such as downloading
      asset. Defaults to the token provided by GitHub Actions environment.
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Collect info
      id: info
      run: |
        echo "bin-installed=$(if command -v umka >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
        bin_dir="umka_$(date +%s)"
        bin_path="${GITHUB_WORKSPACE}/${bin_dir}"
        mkdir -p "${bin_path}"
        echo "bin-dir=${bin_dir}" >> "$GITHUB_OUTPUT"
        echo "bin-path=${bin_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download binary
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: download-binary
      uses: robinraju/release-downloader@v1
      with:
        repository: "vtereshkov/umka-lang"
        latest: "${{ inputs.version == 'latest' }}"
        tag: "${{ inputs.version == 'latest' && '' || format('v{0}', inputs.version) }}"
        fileName: "umka_*_${{ runner.os == 'Linux' && 'linux' || 'windows_mingw' }}.zip"
        extract: "true"
        out-file-path: "${{ steps.info.outputs.bin-dir }}"
        token: "${{ inputs.github-token }}"
    - name: Install umka
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      run: |
        tag_name="${{ steps.download-binary.outputs.tag_name }}"
        bin_path="${{ steps.info.outputs.bin-path }}/umka_${tag_name#v}_${{ runner.os == 'Linux' && 'linux' || 'windows_mingw' }}"
        if [ "${RUNNER_OS}" != "Windows" ]; then
          chmod +x "${bin_path}/umka"
        fi
        echo "${bin_path}" >> "$GITHUB_PATH"
      shell: sh
