---
name: "Setup Umka"
author: Yevhen Fabizhevskyi
description: "This action sets up Umka scripting language interpreter."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "Umka version."
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Collect info
      id: info
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: ./collect-info.sh "${INPUT_VERSION}"
      shell: sh
      working-directory: "${{ github.action_path }}"
    - name: Download umka
      if: ${{ steps.info.outputs.umka-installed == 'false' }}
      uses: robinraju/release-downloader@v1.9
      with:
        repository: vtereshkov/umka-lang
        latest: ${{ inputs.version == 'latest' }}
        tag: ${{ inputs.version == 'latest' && '' || format('v{0}', inputs.version) }}
        fileName: ${{ steps.info.outputs.file-name }}.zip
        tarBall: false
        zipBall: false
        out-file-path: umka
    - name: Install umka
      if: ${{ steps.info.outputs.umka-installed == 'false' }}
      run: |
        ./install-umka.sh \
          "${{ steps.info.outputs.file-name }}" \
          "${{ steps.info.outputs.umka-path }}"
      shell: sh
      working-directory: "${{ github.action_path }}"
