---
name: "Setup Umka"
author: Yevhen Fabizhevskyi
description: "This action sets up Umka scripting language interpreter."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "Umka version."
    required: false
    default: "latest"
  token:
    description: "The GitHub token or personal access token"
    required: false
    default: "${{ github.token }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh
    - name: Collect info
      id: info
      run: ./collect-info.sh
      shell: sh
      working-directory: "${{ github.action_path }}/src"
    - name: Download umka
      if: ${{ steps.info.outputs.umka-installed == 'false' }}
      id: release
      uses: robinraju/release-downloader@v1.9
      with:
        repository: vtereshkov/umka-lang
        latest: ${{ inputs.version == 'latest' }}
        tag: ${{ inputs.version == 'latest' && '' || format('v{0}', inputs.version) }}
        fileName: "umka_*${{ runner.os == 'Linux' && 'linux' || 'windows' }}*"
        zipBall: true
        out-file-path: umka
        extract: true
        token: "${{ inputs.token }}"
    - name: Install umka
      if: ${{ steps.info.outputs.umka-installed == 'false' }}
      run: |
        echo "${{ steps.release.outputs.downloaded_files }}"
        echo "====="
        ls -la ${GITHUB_WORKSPACE}
        echo "====="
        ls -la ${GITHUB_WORKSPACE}/umka
        echo "====="
        ls -la ${GITHUB_WORKSPACE}/umka/umka_1.3.1_linux
        ./install-umka.sh \
          "${{ steps.info.outputs.file-name }}" \
          "${{ steps.info.outputs.umka-path }}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"
