---
name: "Setup Umka"
author: Yevhen Fabizhevskyi
description: "This action sets up Umka scripting language interpreter."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "Umka version."
    required: false
    default: "1.2"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'macOS' }}
      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
      shell: sh
    - name: Collect info
      if: ${{ runner.os != 'macOS' }}
      id: info
      run: |
        if [ "${RUNNER_OS}" = "Linux" ]; then
          UMKA_BINARY=linux
          UMKA_EXEC=umka
        else
          UMKA_BINARY=windows_mingw
          UMKA_EXEC=umka.exe
        fi
        echo "UMKA_BINARY=${UMKA_BINARY}" >> $GITHUB_OUTPUT
        echo "UMKA_INSTALLED=$(if command -v "${UMKA_EXEC}" >/dev/null 2>&1; then echo true; else echo false; fi)" >> "$GITHUB_OUTPUT"
        mkdir -p "${GITHUB_WORKSPACE}/umka"
        echo "UMKA_PATH=${GITHUB_WORKSPACE}/umka" >> $GITHUB_OUTPUT
      shell: sh
    - name: Download umka
      if: ${{ steps.info.outputs.UMKA_INSTALLED == 'false' }}
      uses: robinraju/release-downloader@v1.8
      with:
        repository: vtereshkov/umka-lang
        latest: false
        tag: v${{ inputs.version }}
        fileName: umka_${{ inputs.version }}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip
        tarBall: false
        zipBall: false
        out-file-path: umka
    - name: Install umka
      if: ${{ steps.info.outputs.UMKA_INSTALLED == 'false' }}
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: |
        unzip "umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip"
        rm -f "umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}.zip"
        if [ "${RUNNER_OS}" != "Windows" ]; then
          chmod +x "${{ steps.info.outputs.UMKA_PATH }}/umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}/umka"
        fi
        echo "${{ steps.info.outputs.UMKA_PATH }}/umka_${INPUT_VERSION}_x86-64_${{ steps.info.outputs.UMKA_BINARY }}" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.UMKA_PATH }}
