---
name: 'Setup Umka'
author: Yevhen Fabizhevskyi
description: 'This action sets up Umka scripting language interpreter.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Umka version.'
    required: false
    default: 0.4.1
runs:
  using: 'node12'
  main: 'dist/index.js'
