---
name: Sync labels

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - fix/labels-sync
  #    paths:
  #      - .github/labels.yml
  workflow_dispatch:

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
